---
- name: Create and format ext4 logical volumes
  when: cis | bool or item.lv not in ['home', 'var', 'var_log', 'var_log_audit']
  community.general.filesystem:
    dev: /dev/sys/{{ item.lv }}
    fstype: ext4
    force: true
  loop:
    - { lv: root }
    - { lv: home }
    - { lv: var }
    - { lv: var_log }
    - { lv: var_log_audit }
